# permissions for end users to view opentelemetryagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetryagent-viewer-role
rules:
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetryagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetryagents/status
  verbs:
  - get
