# permissions for end users to edit opentelemetrycollectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetrycollector-editor-role
rules:
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetrycollectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetrycollectors/status
  verbs:
  - get
