# permissions for end users to view opentelemetrycollectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetrycollector-viewer-role
rules:
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetrycollectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetrycollectors/status
  verbs:
  - get
