---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetryagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetryagents/finalizers
  verbs:
  - update
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetryagents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetrycollectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetrycollectors/finalizers
  verbs:
  - update
- apiGroups:
  - otel.mzx.org
  resources:
  - opentelemetrycollectors/status
  verbs:
  - get
  - patch
  - update
